version: "3"
services:
  vote:
    image: franky0777/voting-app-vote:latest
    build:
      context: ./vote
    ports:
      - "5000:443"
    depends_on:
      - redis
    mem_limit: 512m
    networks:
      - app-network
  result:
    image: franky0777/voting-app-result:latest
    build:
      context: ./result
    ports:
      - "5001:443"
    depends_on:
      - postgres
    mem_limit: 512m
    networks:
      - app-network
  worker:
    image: franky0777/voting-app-worker:latest
    build:
      context: ./worker
    depends_on:
      - redis
      - postgres
    mem_limit: 512m
    networks:
      - app-network
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=votes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    mem_limit: 512m
    networks:
      - app-network
  redis:
    image: redis:alpine
    mem_limit: 256m
    networks:
      - app-network
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=postgres
      - SONAR_JVM_OPTS=-Xmx1g
    mem_limit: 2048m
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
    networks:
      - app-network
  jenkins:
    image: franky0777/jenkins:latest
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_EMAIL=m39624112@gmail.com
    mem_limit: 1024m
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db-data:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
