version: '3'
services:
  vote:
    build: ../vote
    image: franky0777/vote:v1
    ports:
      - "5000:80"
  result:
    build: ../result
    image: franky0777/result:v1
    ports:
      - "5001:80"
  worker:
    build: ../worker
    image: franky0777/worker:v1
